/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.core.util.LoggerManager;
import com.dts.crsm.dao.InventoryDAO;
import com.dts.crsm.model.Inventory;

/** 
 * MyEclipse Struts
 * Creation date: 12-24-2008
 * 
 * XDoclet definition:
 * @struts.action
 */
public class AddNewInventory extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
			
		   
		      try
		      {
		           Inventory inventory = (Inventory)form;
		          
		         // inventory.setBrandID(brandid);
		              
		          
		           boolean flag = new InventoryDAO().addInventory(inventory);
		      if(flag)
		      {
		    	  return mapping.findForward("registerSuccess");
		      }
		      }
		          catch(Exception e)
		          {e.printStackTrace();
		             LoggerManager.writeLogWarning(e);
		          }
		          return mapping.findForward("registerFail");  
	
	}
}