/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.crsm.dao.ItemDAO;
import com.dts.crsm.model.Item;

/** 
 * MyEclipse Struts
 * Creation date: 12-24-2008
 * 
 * XDoclet definition:
 * @struts.action path="/addNewItem" name="item" scope="request" validate="true"
 */
public class AddNewItem extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try{
			Item item = (Item) form;// TODO Auto-generated method stub
			ItemDAO aItemDAO = new ItemDAO();
        	boolean flag = aItemDAO.addItem(item);
        	if(flag)
        	{
        		return mapping.findForward("registerSuccess");
        	}}catch (Exception e) {
				// TODO: handle exception
			}
        	return mapping.findForward("registerFail");
}
}