/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.crsm.dao.ItemDAO;
import com.dts.crsm.model.Item;

/** 
 * MyEclipse Struts
 * Creation date: 12-24-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class EditItemAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			Item aItem=(Item)form;
			ItemDAO aItemDAO = new ItemDAO();
        	boolean flag = aItemDAO.updateItem(aItem);
		if(flag)
		{
			return mapping.findForward("updateSuccess");
		}
		}catch (Exception e) {
			// TODO: handle exception
		}
		return mapping.findForward("updateFail");
	}
}