/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.core.util.CoreHash;
import com.dts.crsm.dao.OrdersDAO;

/** 
 * MyEclipse Struts
 * Creation date: 01-23-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ViewCustomerOrdersAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			HttpSession session=request.getSession();
			String loginName =(String)session.getAttribute("user");
			CoreHash aCoreHash = new OrdersDAO().listOrders(loginName);
		int size=aCoreHash.size();
		if(size!=0)
		{
			request.setAttribute("viewCoreHash",aCoreHash);
			return mapping.findForward("viewCustomerOrders");
		}
		}catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		}
		return mapping.findForward("norecords");
	}
}