/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.dae.dao.SecurityDAO;
import com.dts.dae.model.Profile;

/** 
 * MyEclipse Struts
 * Creation date: 12-23-2008
 * 
 * XDoclet definition:
 * @struts.action
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
			try{
				HttpSession session=request.getSession();
			
			 Profile  rb=(Profile)form;
			 
	         String role=new SecurityDAO().loginCheck(rb);
	         System.out.println("role..."+role);
	        
	         if(role.equals("admin"))
	         { 
	             session.setAttribute("user",rb.getLoginID());
	            session.setAttribute("role",role);
	            return mapping.findForward("adminhome");
	        	
	         } 
	           else if(role.equals("customer"))
	         { 
	        	   session.setAttribute("user",rb.getLoginID());
		            session.setAttribute("role",role);
		        
	        	   return mapping.findForward("customer");
	             } 
	           else if(role.equals("dealer"))
		         { 
		        	   session.setAttribute("user",rb.getLoginID());
			            session.setAttribute("role",role);
			        
		        	   return mapping.findForward("dealer");
		             } 
	           else if(role.equals("Employee"))
		         { 
		        	   session.setAttribute("user",rb.getLoginID());
			            session.setAttribute("role",role);
			        
		        	   return mapping.findForward("Employeehome");
		             } 
	         else  
	        	   return mapping.findForward("norecords");
	            }catch(Exception e){e.printStackTrace();} 
	     	   return mapping.findForward("norecords");
		        
		}
	
}