/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.crsm.dao.CategoryDAO;
import com.dts.crsm.model.Category;

/** 
 * MyEclipse Struts
 * Creation date: 12-24-2008
 * 
 * XDoclet definition:
 * @struts.action path="/updateCategory" name="category" scope="request"
 */
public class UpdateCategory extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try{
			Category category = (Category) form;// TODO Auto-generated method stub
		
		CategoryDAO aCategoryDAO = new CategoryDAO();
    	boolean flag = aCategoryDAO.updateCategory(category);
    	if(flag)
    	{
    		return mapping.findForward("updateSuccess");
    	}
	}catch (Exception e) {
		// TODO: handle exception
	}
	return mapping.findForward("updateFail");
}
}